// <auto-generated />
namespace futTentativaDois.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addoutroscampos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addoutroscampos));
        
        string IMigrationMetadata.Id
        {
            get { return "202504181738138_add-outros-campos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
